### ISSUE TITLE
Composer scripts output not being saved

### ISSUE THREAD

**Issue by reed-jones** [juicyfx/vercel-php#102]
# Bug report

- Version: vercel-php@0.3.1
- URL: https://phase-blog-demo-git-v050-upgrade.reedjones.now.sh/
- Repository: https://github.com/reed-jones/phase-blog-demo/pull/7

## Description
Composer scripts run perfectly (thanks!)
```
        "vercel": [
            "npm install",
            "npm  run prod"
        ]
```

However the build output (js/css) isn't available after the build is complete. If it helps, I'm using laravel mix

```
21:03:07.975 | > cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
21:03:20.083 | DONE  Compiled successfully in 10120ms3:03:20 AM
21:03:20.087 | Asset       Size  Chunks                    Chunk Names
21:03:20.087 | /css/app.css   8.47 KiB       1  [emitted]         /js/app-server
21:03:20.087 | /js/app-client.js    169 KiB       0  [emitted]         /js/app-client
21:03:20.087 | /js/app-client.js.LICENSE.txt  219 bytes          [emitted]
21:03:20.087 | /js/app-server.js    326 KiB       1  [emitted]  [big]  /js/app-server
21:03:20.087 | /js/app-server.js.LICENSE.txt  219 bytes          [emitted]
21:03:20.157 | 🐘 Running composer scripts [DONE]
21:03:28.993 | 🐘 Creating lambda
21:03:36.877 | Uploading build outputs...
21:03:40.526 | Build completed. Populating build cache...
21:03:48.266 | Uploading build cache [26.75 MB]...
21:03:48.921 | Build cache uploaded: 662.765ms
21:03:48.931 | Done with "api/index.php"
```
(apologies for the formatting on that)

however `/css/app.css` and `/js/app-client.js` return 404's when the site is loaded (website if I run `npm run prod` locally and commit the output to git: https://phase-blog-demo.now.sh/)

**Comment by f3l1x** [comment]
Hi @reed-jones. 

I think there could be a problem with routing. Could you show me your routes? 

You should use filesystem routing or set route css/js to assets folder.

```
{
  "routes": [
    { "handle": "filesystem" },
    ....
  ]
}
```

Take a look at https://vercel.com/docs/configuration#routes/advanced/wildcard-routes.

---

Btw, thanks for sponsoring me.

**Comment by reed-jones** [comment]
👍  Thanks for your work!

I don't _think_ its routing, since I can run `composer run vercel` locally to build the files, (they are saved to the 'public' folder, and if I add these files to git, my routing works as expected

```
    "routes": [
      { "src": "/(.*)\\.(.*)$", "dest": "public/$1.$2"},
      { "src": "/(.*)",  "dest": "/api/index.php" }
    ],
```

following your suggestion, I tried
```
   "routes": [
      { "handle": "filesystem" },
      { "src": "/(.*)",  "dest": "/api/index.php" }
    ],
```
and
```
    "routes": [
      { "src": "/css/app.css",  "dest": "/public/css/app.css" },
      { "src": "/(.*)",  "dest": "/api/index.php" }
    ],
```
neither of which seem to be working (just returning 404). I'm not sure how vercel's build system really works, but could it be possible the files aren't persisted to disk, or got saved to `/tmp` or something?

**Comment by f3l1x** [comment]
Hmm, I think I know where is the catch. Files created in build phase (during call `composer run vercel`) are not accessible from browser/routing/routes.

I solved it with little trick in satis example.

https://github.com/juicyfx/vercel-examples/blob/d615f48830491e54afba30d0e54f402a6e6ccc0e/php-satis/index.php#L3-L9

I am in touch with Vercel team. For now, test please this approach.

**Comment by reed-jones** [comment]
awesome thanks, I'll try this soon

**Comment by reed-jones** [comment]
Works great, thanks for the idea.

**Comment by f3l1x** [comment]
I placed it to readme. Thanks for the issue.

**Comment by guoxiangke** [comment]
@f3l1x  Can you give a example of assets.php, thanks.
<img width="708" alt="image" src="https://user-images.githubusercontent.com/1160703/147515493-98f9d586-0568-4ee2-b91d-d6b82d84f435.png">
