### ISSUE TITLE
Entire project is sent to each builder

### ISSUE THREAD

**Issue by unitof** [juicyfx/vercel-php#103]
# Bug report

- Version: `0.3.1`
- URL: https://vercel.com/unitof/php-root-bug/li430s3wp (see build logs)
- Repository: https://github.com/unitof/vercel-examples/tree/builder-rootfiles-bug/php-root-bug

## Description

It appears that all files in the now Vercel project root (where `.vercel` and/or `now.json` are kept) are being sent to the builder for each Serverless Function. It's causing my builds to fail, as my repo as a whole is well over the Lambda max of 50MB, even though each Serverless function is well below that.

My understanding is that each Serverless Function should, by default, include only its own `.php` file, plus any matching files explicitly specified in that function's `includeFiles` in `now.json`.

The example at the repo above is nearly identical to the [vercel-examples/php](https://github.com/juicyfx/vercel-examples/tree/master/php) example, just with a 100MB nonsense zip file added to the root directory. It fails to build because `Error: The Serverless Function "api/index.php" is 127.22mb which exceeds the maximum size limit of 50mb. Learn More: https://vercel.link/serverless-function-size`.

**Comment by reed-jones** [comment]
(If I'm understanding properly) I think thats intended. For example check out the Lumen example: https://github.com/juicyfx/vercel-examples/tree/master/php-lumen `api/index.php` just pulls in the main lumen app entry file from the root of the project.

I'm not sure, but maybe adding your zip to the ~.nowignore~ .vercelignore would work? https://vercel.com/guides/prevent-uploading-sourcepaths-with-vercelignore

**Comment by f3l1x** [comment]
It's the feature. You must use `. vercelignore` and ignore all files/folders you don't want to upload.

**Comment by unitof** [comment]
Gotcha, my mistake then. I didn't realize each function gets the context of the entire repo by default.

I don't want to `.vercelignore` the files in my root, as I want them to be served statically, but I'll use `excludeFiles` instead.

Which does lead me to a new bug, which I'll report separately: Vercel now requires `includeFiles` and `excludeFiles` to be a single glob pattern, but `vercel-php` still expects arrays.
