### ISSUE TITLE
Does not support includeFiles and excludeFiles glob patterns, which Vercel requires

### ISSUE THREAD

**Issue by unitof** [juicyfx/vercel-php#104]
# Bug report

- Version: `0.3.1`
- URL: https://juicyfx-php-test.unitof.vercel.app/api/index.php (& its [function logs](https://vercel.com/unitof/juicyfx-php-test/6mnqiimpk/functions?name=z9nQ0UbzQf52vfYODE78vvVk-1cf83ce6e5608a42ec3eb0bdc9cdb051a8d831a))
- Repository: https://github.com/unitof/vercel-examples/tree/builder-glob-bug/php-excludeFiles-bug

## Description

Vercel requires a function's `includeFiles` and `excludeFiles` to be a [single glob string](https://vercel.com/docs/configuration#project/functions).

`vercel-php` expects an [array](https://github.com/juicyfx/vercel-php#%EF%B8%8F-faq), or a string. But it trips on many glob matching patterns.

There are two abutting issues:

1. A ~`now.json`~`vercel.json` file with an array in `includeFiles` or `excludeFiles` fails validation and refuses to deploy, even though that's what's recommended in `vercel-php`'s documentation.

```
Error! Invalid now.json - `functions['api/index.php'].excludeFiles` Invalid request: `functions['api/index.php'].excludeFiles` should be string..
```

2. `vercel-php` seems to trip on many non-trivial glob patterns (basically anything that's beyond a string ending in `*` or `**`). It will deploy, but with the following behavior:

On the first GET request, the request times out with a Vercel 502 `NO_RESPONSE_FROM_FUNCTION` error.
<img width="1470" alt="image" src="https://user-images.githubusercontent.com/2448782/89663092-0433e480-d8a3-11ea-9efb-68477f963ef4.png">

Vercel logs show the following:

```
🐘 Spawning: PHP Built-In Server at /var/task/user (document root) and /var/task/user/api/index.php (router)
2020-08-07T15:41:38.840Z	d9691f0f-b896-4a65-8b9e-2182919131a0	ERROR	🐘STDERR: Directory /var/task/user does not exist.
🐘 PHP Built-In Server process closed code 1 and signal null
2020-08-07T15:41:43.570Z	d9691f0f-b896-4a65-8b9e-2182919131a0	ERROR	Invoke Error 	{"errorType":"Error","errorMessage":"connect ECONNREFUSED 127.0.0.1:8000","code":"ECONNREFUSED","errno":"ECONNREFUSED","syscall":"connect","address":"127.0.0.1","port":8000,"stack":["Error: connect ECONNREFUSED 127.0.0.1:8000","    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)"]}
```

On all subsequent requests, PHP returns `PHP Built-In Server HTTP error: Error: connect ECONNREFUSED 127.0.0.1:8000`.

<img width="1470" alt="image" src="https://user-images.githubusercontent.com/2448782/89664944-e451f000-d8a5-11ea-9523-5d7df8bf9506.png">

Vercel logs show:

```
🐘 Accessing juicyfx-php-test-nl5ugs3i9.vercel.app/api/index.php
🐘 Querying /api/index.php
2020-08-07T15:43:47.070Z	bf4f302d-3817-4f32-b291-e81deaf3274f	ERROR	🐘 PHP Built-In Server HTTP errored Error: connect ECONNREFUSED 127.0.0.1:8000
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16) {
  errno: 'ECONNREFUSED',
  code: 'ECONNREFUSED',
  syscall: 'connect',
  address: '127.0.0.1',
  port: 8000
}
```

My temporary workaround is to use a single string with a simple glob pattern that `vercel-php` _does_ seem to do okay with; in my case: `excludeFiles: projects/**`.

Glob patterns I've encountered this issue with:
`!(file)`
`(fileA|fileB)` (doesn't error, but appears to get parsed as a single exact filename, rather than a glob pattern)
`**/*`

**Comment by f3l1x** [comment]
Hi, thanks for great report.

I have tested current version (0.3.1) and it works.

- includeFiles is not supported, only excludeFiles
- you can use string in excludedFiles (fixed in readme, thx)
- you can combine .vercelignore with excludedFiles easily (take a look at example)

Take a look at my examples (https://github.com/juicyfx/vercel-php/tree/master/test/examples/18-exclude-files)

**Comment by unitof** [comment]
Aha! That likely explains my issues: I was using a `excludeFiles: "**/*"` and assuming `includeFiles` would then act as an allowlist, but in reality I was just excluding _everything_, probably the underlying cause of the PHP errors.

Will see if I can construct an `excludeFiles` glob that does what I need! (Basically, to exclude everything except one common `api/functions.php` file from each function's builder.)

**Comment by f3l1x** [comment]
Yep, that's catchy. :-)

Vercel is using [glob](https://www.npmjs.com/package/glob) and it's using [minimatch](https://www.npmjs.com/package/minimatch). You can test it here https://globster.xyz/.

**Comment by f3l1x** [comment]
I am closing it now, feel free open it again.
