### ISSUE TITLE
Session usage

### ISSUE THREAD

**Issue by lekoala** [juicyfx/vercel-php#118]
# Question

So I'm experimenting with vercel and I'm wondering if session usage is supposed to work (since it's serverless?)

So far, it seems to work but I get something a bit strange

Using the following code

```
session_start();

$counter = $_SESSION['counter'] ?? 0;
$counter++;
$_SESSION['counter'] = $counter;

echo "counter is $counter";
```

I got an increment of 1 on my local webserver, but an increment of 2 of my test application running on vercel. No idea why. More generally I'm wondering what happens to temporary files (uploaded files? session files?) when running the php backend.

I know it's a bit outside of vercel-php itself but I'm guessing I may not the only one askying myself these questions?

**Comment by f3l1x** [comment]
Hi @lekoala.

It happends after deployment, because Vercel is taking screenshot of your app, thus there is +1 visit. But it should happen only after deployment.

**Comment by lekoala** [comment]
actually i think it may simply due to an oversight on my end and the the favicon request was counted as well :-) closing the issue

**Comment by f3l1x** [comment]
Yup, favicon is also extra request, you're right.
