### ISSUE TITLE
php with vercel

### ISSUE THREAD

**Issue by fivenine01** [juicyfx/vercel-php#121]
# not sure what im doing wrong while following the steps listed

Here's a  3 min video of what i'm doing and the error im getting... im new to php and github, can someone please let me know where i go wrong?
https://youtu.be/_XMPR79AOgA

**Comment by JosBroers** [comment]
You don't need to implement the following in your PHP code, because it's an example and shows information of the php settings you are using. [phpinfo — Outputs information about PHP's configuration](https://www.php.net/manual/en/function.phpinfo.php):
```php
<?php
phpinfo();
```
You're installing Vercel not globally... Try that:
```shell
# Install it globally
npm i -g vercel

# Log in
vercel login

# Let's fly
vercel
```

**Comment by f3l1x** [comment]
Hi @fivenine01. It seems to me there is some error in your editor/OS. Vercel CLI should be working without problem. 

Have you followed this manual (https://vercel.com/download)? If it so, could you please reach Vercel's support team?

**Comment by fivenine01** [comment]
> You don't need to implement the following in your PHP code, because it's an example and shows information of the php settings you are using. [phpinfo — Outputs information about PHP's configuration](https://www.php.net/manual/en/function.phpinfo.php):
> 
> ```
> <?php
> phpinfo();
> ```
> 
> You're installing Vercel not globally... Try that:
> 
> ```shell
> # Install it globally
> npm i -g vercel
> 
> # Log in
> vercel login
> 
> # Let's fly
> vercel
> ```

hey thanks for that, I completely thought I had replied, but thank you for that, it worked!

**Comment by f3l1x** [comment]
Happy to hear that.
