### ISSUE TITLE
Is Vercel's .env CLI compatible with vercel-php?

### ISSUE THREAD

**Issue by Borumer** [juicyfx/vercel-php#125]
# Question

Are the `vercel env` commands usable for the vercel-php runtime? I want to store some secrets that are encrypted through Vercel. They are stored in my gitignored `.env` file. Can I access this in PHP?

**Comment by f3l1x** [comment]
Hi. Yup, Environment Variables are supported. :-) 

- It works seamless on Vercel platform, after deployment.
- Locally, it depends as you start your local development server.
    - `SOME_ENV=foo php -S localhost:8000 api/index.php`

**Comment by Borumer** [comment]
How do we access these variables in PHP? The docs only talk about JavaScript

**Comment by Borumer** [comment]
I am going to try using PHP's `$_ENV`

**Comment by f3l1x** [comment]
Yes, use `$_ENV` or `getenv()`.

I will put it on vercel-php doc.

**Comment by Borumer** [comment]
Thank you very much!
