### ISSUE TITLE
Question: how to use multiple php files in /api folder

### ISSUE THREAD

**Issue by eFrostByte** [juicyfx/vercel-php#138]
# Is it possible to have folders inside /api?

I'm trying to make a game with un/pw authentication using php. In this game, each level has a url.
Using vercel-php, I was thinking in something like this:

game.vercel.app/api/index.php --> home page
game.vercel.app/api/level1/hint1.php
game.vercel.app/api/level2/hint2.php
...
I tried editing the vercel.json like this:
~~~
"api/*/*.php" 
~~~ 
but it didn't work.

Is it possible to do this?

**Comment by f3l1x** [comment]
Hi, yep, it is possible.

```json
{
  "functions": {
    "api/**/*.php": {
      "runtime": "vercel-php@0.3.1"
    }
  }
}
```

Can you test this?

**Comment by eFrostByte** [comment]
Ah, yes. Thanks!

**Comment by f3l1x** [comment]
Glad to help. :-)
