### ISSUE TITLE
Cannot run @php artisan command in composer script(s)

### ISSUE THREAD

**Issue by satyakresna** [juicyfx/vercel-php#141]
Hi @f3l1x, When I deploy Laravel project version 8.x and run command `@php artisan migrate --force` in composer script(s) it get error message like this:

```
In Application.php line 690:
Class 'Facade\Ignition\IgnitionServiceProvider' not found
```

I check in vercel log deployment I don't see that the package `facade/ignition` installed. The package `facade/ignition` is located in `require-dev` **composer.json**. Is that possible to run `composer install` include `required-dev` package?

**Comment by f3l1x** [comment]
Hi. Dev dependencies are not installed.

**Comment by satyakresna** [comment]
Noted, thanks @f3l1x, I think I will run `artisan` command from Laravel Controller instead of run in `vercel` composer script.
