### ISSUE TITLE
Bundling gRPC Extension

### ISSUE THREAD

**Issue by CRYPTO-4N0M4LY** [juicyfx/vercel-php#151]
# Feature Request
Hi, is it possible to bundle/include gRPC extension with the runtime?
https://blog.remirepo.net/pages/PECL-extensions-RPM-status page lists the extension.

Thanks!

**Comment by f3l1x** [comment]
![image](https://user-images.githubusercontent.com/538058/112656757-fe027080-8e51-11eb-8fc1-2ee502918db2.png)

Done. Just re-deploy. :-)

**Comment by CRYPTO-4N0M4LY** [comment]
You're amazing.
Thanks!
Is there a donation option?

**Comment by f3l1x** [comment]
Yup, https://github.com/sponsors/f3l1x

Thank you.
