### ISSUE TITLE
[question] How can I write files

### ISSUE THREAD

**Issue by boyphongsakorn** [juicyfx/vercel-php#154]
# Question

can i write txt file on php?

i use fwrite function but not work.

can be another function to write a txt file?

**Comment by f3l1x** [comment]
Hi. You can write only to `/tmp` folder. All other folders are non-writable.

**Comment by boyphongsakorn** [comment]
oh thank you

**Comment by boyphongsakorn** [comment]
where iss /tmp folder?
inside /api folder or inside home of os?

**Comment by f3l1x** [comment]
It’s on OS level. So /tmp.

**Comment by boyphongsakorn** [comment]
oh thank you again
