### ISSUE TITLE
[question] How to access Vercel Environment Variables?

### ISSUE THREAD

**Issue by 4t2py** [juicyfx/vercel-php#156]
How to access Vercel Environment Variables?

**Comment by f3l1x** [comment]
Hello. Try to dump `$_SERVER` or `$_ENV`. They should be there.

**Comment by varunsingh87** [comment]
Environmental variables using the vercel-php runtime work the same way as they normally do on Vercel. 

Follow the steps from the [docs](https://vercel.com/docs/environment-variables), outlined below:

1. Go to Project Settings
2. Set a Production, Preview, or Development variable name and value
3. Click Add

On the deploy Vercel build, use `$_ENV["NAME OF VARIABLE"]`

For local development, store them in a `.env` file that is gitignored, then install and use [dotenv](https://github.com/vlucas/phpdotenv) to load them into the `$_ENV` variable.
