### ISSUE TITLE
Does this project comply with TOS 

### ISSUE THREAD

**Issue by am-abudu** [juicyfx/vercel-php#158]
# Question
Does this project comply with TOS ? I am afraid of it. ^_^

**Comment by f3l1x** [comment]
What do you mean with TOS?

**Comment by am-abudu** [comment]
> What do you mean with TOS?

It is Terms of Service
https://vercel.com/legal/terms

**Comment by f3l1x** [comment]
Why do you think it's not comply with TOS?

**Comment by evansims** [comment]
Yep, it's perfectly fine with their terms of service, as long as what you're running isn't violating [their fair use policy](https://vercel.com/docs/platform/fair-use-policy). 👍  They even write about using it [on the Vercel blog](https://vercel.com/blog/customizing-serverless-functions).

**Comment by f3l1x** [comment]
Yes it does.
