### ISSUE TITLE
Install geoip by default.

### ISSUE THREAD

**Issue by PugzAreCute** [juicyfx/vercel-php#174]
# Feature Request

Please install geoip ([http://pecl.php.net/package/geoip](http://pecl.php.net/package/geoip)) by default.

**Comment by f3l1x** [comment]
Will do.

**Comment by f3l1x** [comment]
Done. Can you please test it?

**Comment by f3l1x** [comment]
<img width="1109" alt="image" src="https://user-images.githubusercontent.com/538058/162588204-73806e1e-8420-4d87-8b14-437374d47135.png">

**Comment by PugzAreCute** [comment]
Works for me!
