### ISSUE TITLE
file_get_contents does not work with files on my website

### ISSUE THREAD

**Issue by Tanay360** [juicyfx/vercel-php#180]
Errors are thrown in my php file while I am using file_get_contents

**Comment by f3l1x** [comment]
Hi @Tanay360. Can you share your code and exception?

**Comment by Tanay360** [comment]
Here is the repository:
https://github.com/Tanay360/tanay360users

And the error can be seen here:
https://tanay360users.vercel.app/api/usersrec.php?start=1

**Comment by f3l1x** [comment]
It's because of your vercel.json. It uploads only PHP files.

```
{
  "functions": {
    "api/*.php": {
      "runtime": "vercel-php@0.4.0"
    }
  }
}
```

Try to create `src/users.json` and load them. It should fix it.

**Comment by Tanay360** [comment]
@f3l1x I tried, but the result is the same

**Comment by f3l1x** [comment]
It works.

Demo: https://20-read-files-f3l1x-xorg.vercel.app
Source: https://github.com/juicyfx/vercel-php/commit/0e33bb8f40f985b214cd82a00c26aa416b030fae

**Comment by qkqpttgf** [comment]
> It works.
> 
> Demo: https://20-read-files-f3l1x-xorg.vercel.app
> Source: [0e33bb8](https://github.com/juicyfx/vercel-php/commit/0e33bb8f40f985b214cd82a00c26aa416b030fae)

#183 , sorry but this demo is error too.

**Comment by f3l1x** [comment]
@qkqpttgf That's weird. I have to re-deploy it and now it works.

**Comment by qkqpttgf** [comment]
> @qkqpttgf That's weird. I have to re-deploy it and now it works.

I told, it works for a few hours, if no one visit some time, it will error

**Comment by Tanay360** [comment]
@qkqpttgf can you please add an example for writing files as well? 😀

**Comment by f3l1x** [comment]
Only /tmp folder is writable.

`file_put_contents('/tmp/file.txt');`

**Comment by Tanay360** [comment]
Thanks! 🙂

**Comment by qkqpttgf** [comment]
> @qkqpttgf can you please add an example for writing files as well? 😀

I copy code folder to /tmp, and write config to config file, and then deploy the folder :)
code deploy itself (ofcourse, provide it a key)
