### ISSUE TITLE
No such file or directory in Unknown

### ISSUE THREAD

**Issue by qkqpttgf** [juicyfx/vercel-php#183]
Hello,
the project is https://github.com/qkqpttgf/OneManager-php ,
deploy: https://scfonedrive.github.io/Vercel/Deploy.html ,
my app: https://verceltest-ysun.vercel.app/ .

I deploy the project, it works at that time,
but,
atfer a few hours, (not visit for one night), it show `
Warning: Unknown: Failed to open stream: No such file or directory in Unknown on line 0

Fatal error: Failed opening required '/var/task/user/index.php' (include_path='.:/opt/remi/php80/root/usr/share/pear:/opt/remi/php80/root/usr/share/php:/usr/share/pear:/usr/share/php') in Unknown on line 0
`
the vercel see `that is not supported by Vercel's support team`,
what can I do now？

**Comment by f3l1x** [comment]
Can you test redeploy?

**Comment by qkqpttgf** [comment]
> Can you test redeploy?

tested, it work after deploy, but error after some hours( I dont know how many hours)

**Comment by f3l1x** [comment]
I will reach Vercel team and we will see.

**Comment by qkqpttgf** [comment]
> I will reach Vercel team and we will see.

the demo in #180 is error now, after some hours, 
so, help.
thank you.

**Comment by qkqpttgf** [comment]
Hello?

**Comment by boyphongsakorn** [comment]
> Hello?

i have a same error as you. do you have a solution at now?

**Comment by f3l1x** [comment]
Does it still an issue? I've tested it again and it works seems to me.

**Comment by qkqpttgf** [comment]
> Does it still an issue? I've tested it again and it works seems to me.

It looks work now, how it happen, and what can I do?

**Comment by f3l1x** [comment]
It looks like vercel team fixed runtime API/workflow.
