### ISSUE TITLE
The pattern "*.php" defined in functions doesn't match any Serverless Functions inside the api directory.

### ISSUE THREAD

**Issue by Reallukeisbest** [juicyfx/vercel-php#189]
Hello!

I am trying to upload a website with PHP to Vercel using VercelPHP (https://github.com/juicyfx/vercel-php) but, when trying to build, I get an error on my vercel.php file. The error is: "Error: The pattern "*.php" defined in functions doesn't match any Serverless Functions inside the api directory. Learn More: https://vercel.link/unmatched-function-pattern" and, the vercel.json file looks like this:
```json
{
    "functions": {
        "api/*.php": {
            "runtime": "vercel-php@0.4.0"
        },
        "*.php": {
            "runtime": "vercel-php@0.4.0"
        },
        "dashboard/*.php": {
            "runtime": "vercel-php@0.4.0"
        },
        "api/admin/*.php": {
            "runtime": "vercel-php@0.4.0"
        }
    }
}
```
Thank you for taking the time to read this,
Reallukeisbest

**Comment by f3l1x** [comment]
Only api folder is allowed for `functions`.

**Comment by Reallukeisbest** [comment]
> Only api folder is allowed for `functions`.

How could I combat this problem?

**Comment by fu-sen** [comment]
There is a good Vercel discussion for this answer:
https://github.com/vercel/vercel/discussions/6730

But as you know you got here from the Vercel discussion:
https://github.com/vercel/vercel/discussions/6744

 **This is a Vercel feature, not only vercel-php specific.** So I think the comments you received there made an incorrect transfer.
