### ISSUE TITLE
Example: symfony app

### ISSUE THREAD

**Issue by f3l1x** [juicyfx/vercel-php#19]

**Comment by ties-v** [comment]
What kind of example should this be? The full Symfony demo or some more simple (custom) website using Symfony?

For the full demo website see: https://github.com/ties-v/symfony-demo-on-now and  https://symfony-demo.ties.now.sh/

For a little less advanced example I would be able to put something together.

**Comment by f3l1x** [comment]
I think we should have 2 examples

- tiny minimal example
- full standard example

You can start with the minimal. What do you think?

**Comment by disjfa** [comment]
Having issues to build a symfony app. I don't know what to do with cache on a read only file system. And after that i just get weird errors. So i am tagging along on this thread!

**Comment by f3l1x** [comment]
Hey @disjfa.

Do you have problem with this?

https://github.com/juicyfx/now-examples/tree/master/php-framework-symfony-microservice
https://now-examples-php-framework-symfony-microservice.now.sh/

**Comment by disjfa** [comment]
I used the now files from there yes. But i started with a base symfony 5.0 checkout. So i will update when i have tested this one. If i found what and where we can update and upgrade.

**Comment by disjfa** [comment]
Cool, the trick is to fix the cache folder in your local kernel. For reference for people who read this:

```
public function getCacheDir()
{
    if(isset($_ENV['NOW_REGION'])){
        return '/tmp/symfony/cache/'.$this->environment;
    }

    return parent::getCacheDir();
}

public function getLogDir()
{
    if(isset($_ENV['NOW_REGION'])){
        return '/tmp/symfony/log';
    }

    return parent::getLogDir(); // TODO: Change the autogenerated stub
}
```

Now the next step is to get the static css/js data from the `public/build/` folder on the screen. Can't seem to get that working. Also checked a version 2 of the symfony demo on zeit but still no luck. Tried to fix the routes in the `now.json` to add something like this.

```
{
    "src": "/build/app.css",
    "dest": "/public/build/app.css"
},
```

But no luck, if you have more tips, please. Also when i have something practical i surely will share and blg about it.

**Comment by ties-v** [comment]
@disjfa An example for symfony 4.* is available at [ties-v/symfony-demo-on-now](https://github.com/ties-v/symfony-demo-on-now). 

The [now.json](https://github.com/ties-v/symfony-demo-on-now/blob/master/now.json) file might be interesting to you. 

One thing to notice is that is not using the new keys like `functions`  and `rewrites` etc. Maybe I'll update it some time. 

Hope it helps!

**Comment by disjfa** [comment]
Yes, thats the v2 version i was talking about. I want to add some npm stuff (encore) also so that breaks there for now.

**Comment by ties-v** [comment]
Do you have an example repo somwhere? And what is exactly failing: loading of encore assets?

**Comment by disjfa** [comment]
Pushed my repo, just working on an example to use to prototype. https://github.com/disjfa/symfony-prototype

For now i disabled the encore files and encore build step.

**Comment by f3l1x** [comment]
There are 2 examples of symfony on vercel, take a look https://github.com/juicyfx/vercel-examples.
