### ISSUE TITLE
PSR extension should not be included by default

### ISSUE THREAD

**Issue by WilliamBlais** [juicyfx/vercel-php#213]
# Bug report

- Version: 4.0.0

## Description

The psr extension is incompatible with symfony see https://github.com/symfony/symfony/issues/40870.

The extension author himself requests that the extension be disabled by default, see https://github.com/jbboehr/php-psr/issues/88.

Is it possible to disable it without rebuilding another lib in libphp?

Thanks!

**Comment by f3l1x** [comment]
Hey, you're right. I will disable it completely.

**Comment by 1isten** [comment]
Any update of this issue? I deployed a Laravel 9 project to vercel and got:

```
Fatal error: Declaration of Illuminate\Container\Container::get(string $id) must be compatible with Psr\Container\ContainerInterface::get($id) in /var/task/user/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 702
```

**Comment by sunxyw** [comment]
> 



> Any update of this issue? I deployed a Laravel 9 project to vercel and got:
> 
> ```
> Fatal error: Declaration of Illuminate\Container\Container::get(string $id) must be compatible with Psr\Container\ContainerInterface::get($id) in /var/task/user/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 702
> ```

same issue here. any way to disable the PSR extension?

**Comment by f3l1x** [comment]
Hi. Done. Can you please redeploy your apps?

@sunxyw @HasanMu @1isten @WilliamBlais

**Comment by f3l1x** [comment]
https://github.com/juicyfx/libphp/commit/2a58ea3146024d816a21868eb21e79f829228e86
https://github.com/juicyfx/libphp/commit/6537ba5c0eb338610f20927c5741198eca82566d
https://github.com/juicyfx/libphp/commit/1116c5cc8fbd5b779fb2352705740a3948458fd4
https://github.com/juicyfx/libphp/commit/e8b036cefff3057b98fa04bd5068df1cffa89c8b

**Comment by sunxyw** [comment]
Thanks for your work!
Works great on Laravel 9!

**Comment by 1isten** [comment]
@f3l1x Thank you!
