### ISSUE TITLE
How to work with sessionStorage & localStorage in PHP? 

### ISSUE THREAD

**Issue by ashmanmalik** [juicyfx/vercel-php#218]
# Bug report

session_start(); 
Hey, I am using $_SESSION["variablename"]; and trying to record variable and pass onto the sessions. However, I am unable to do it. Can you suggest a way to do it?

**Comment by WilliamBlais** [comment]
You'd need to use a stateless API or session storage like redis.

**Comment by ashmanmalik** [comment]
Can you give me an example?

**Comment by f3l1x** [comment]
I'm using for example:

- https://fauna.com/
- https://supabase.com/
- https://planetscale.com/
- https://min.io/
