### ISSUE TITLE
Add php-zip extension

### ISSUE THREAD

**Issue by thomas-rooty** [juicyfx/vercel-php#219]
# Feature Request

Would it be possible to add the php-zip extension as it would be very useful to work with tmp file uploading ? I'm building an API that read and write to a temp Excel (xlsx) file and I need to open it using php-zip :

![image](https://user-images.githubusercontent.com/19364687/158987169-4eaf391b-957f-4134-ad46-11e8a24952ea.png)

Is there a way so we can ourselves add an extension to vercel-php ?

Thanks :)

**Comment by f3l1x** [comment]
Hey. Will do. :-)

**Comment by thomas-rooty** [comment]
> Hey. Will do. :-)

Thanks for the fast answer, appreciate it 👍

**Comment by f3l1x** [comment]
Done. Can you please redeploy your apps?

<img width="959" alt="image" src="https://user-images.githubusercontent.com/538058/162588212-21f86a7b-0144-49ec-aee0-4577235d87db.png">
