### ISSUE TITLE
ZEIT -> Vercel

### ISSUE THREAD

**Issue by f3l1x** [juicyfx/vercel-php#58]
- rename now-php to vercel-php?
- rename repositories
- change texts

**Comment by brunosalgueiro** [comment]
I think now is the namo of cli-tool, so I believe that rename to vercel doesn't make sense.

**Comment by fu-sen** [comment]
Yes. ZEIT has changed to Vercel, but Now continues to be used in Now CLI.
I don't think you need to change `now-php` for now.

**Comment by f3l1x** [comment]
Thanks guys. We will see.

I created this issue according the timeline.

https://www.notion.so/83ff48a298f64adaaca85af4f9ab0b57?v=8ae84c07e47740c18e8cc67f6d781f6b

![image](https://user-images.githubusercontent.com/538058/81271851-f032d980-904c-11ea-91bc-d01afe7e1c20.png)

**Comment by fu-sen** [comment]
We were just seeing that change: **Now CLI has been renamed Vercel CLI**.
The command name `now` has changed to` vercel`.
https://github.com/zeit/now/releases/tag/vercel%4019.0.0

It's time to make the decision to completely change the project name.

**Comment by f3l1x** [comment]
PR is ready #62

**Comment by f3l1x** [comment]
Done
