### ISSUE TITLE
MongoDB extension

### ISSUE THREAD

**Issue by nicgutierrez** [juicyfx/vercel-php#92]
# Feature Request

Hi! Is there any chance we could get the [MongoDB](https://pecl.php.net/package/mongodb) extension?

I'm using Laravel and MongoDB but unfortunately the extension is not installed. Cheers!

**Comment by f3l1x** [comment]
Hi, I think it's possible. `mongodb` ext is in REMI's list https://blog.remirepo.net/pages/PECL-extensions-RPM-status. Will do.

**Comment by nicgutierrez** [comment]
Lovely! Thank you @f3l1x : )

**Comment by f3l1x** [comment]
Done. Just redeploy your lambdas (e.q. `now -f`

![16-php-ini-g5ya9ivq7 vercel app_](https://user-images.githubusercontent.com/538058/88486105-a686ca80-cf7b-11ea-99ea-72fca21cb9c8.png)

**Comment by nicgutierrez** [comment]
Hey @f3l1x I can confirm the extension is working - thanks for that! However, I'm getting connection issues and I don't know how easy is going to be do debug or fix... anyhow, this is the error I'm getting:

`"There's been a server error. Please contact the development team. The error is the following: No suitable servers found (`serverSelectionTryOnce` set): [Failed to resolve 'mattoneapi.jvgjd.mongodb.net']"`

Now, the host seems to be up and running in Mongodb Atlas. I've been searching a bit for the error and _it could be_ related to openSSL..

Here's two threads where the issue is discussed:

https://github.com/mongodb/mongo-php-library/issues/313
https://github.com/mongodb/mongo-php-library/issues/575

Any thoughts? Thanks : )

**Comment by f3l1x** [comment]
Hi. Unfortunately I don't use Mongo, so I don't know where is the catch. :-/ 

Maybe you can test it in Docker with similar environment like AWS Lambda is.

https://github.com/juicyfx/libphp/blob/3658080455397a3664d6b77324d158d508b49991/libs/amazon-linux-2-v74/build/Dockerfile#L1-L51
