### ISSUE TITLE
URL rewrite feature

### ISSUE THREAD

**Issue by menjilx** [juicyfx/vercel-php#96]
Hi,
Is there a "demo/example" on how to add URL "rewrite rule"? 
Is Vercel PHP uses NGINX or APACHE? 

Thank you

**Comment by f3l1x** [comment]
Hi, here are docs links:

- https://vercel.com/docs/configuration#project/routes
- https://vercel.com/docs/configuration#project/redirects
- https://vercel.com/docs/configuration#project/rewrites
- https://vercel.com/docs/configuration#routes/src

I don't think they use nginx/apache, their infrastructure is in cloud (AWS lambda).

**Comment by menjilx** [comment]
> Hi, here are docs links:
> 
> * https://vercel.com/docs/configuration#project/routes
> * https://vercel.com/docs/configuration#project/redirects
> * https://vercel.com/docs/configuration#project/rewrites
> * https://vercel.com/docs/configuration#routes/src
> 
> I don't think they use nginx/apache, their infrastructure is in cloud (AWS lambda).

Thank you so much!
