### ISSUE TITLE
SQLite DB

### ISSUE THREAD

**Issue by menjilx** [juicyfx/vercel-php#98]
Hi, is it possible to use SQLite3 database on this version? I tried creating a demo sqlite.db but it doesn't work. Even a simple "connection" test doesn't work or maybe I forgot something? 

Trying to check SQLite version.
`$dbh = new PDO('sqlite::memory:');
print_r("SQLite version " . 
$dbh->query('select sqlite_version()')->fetch()[0]);
$dbh = null;`

`Fatal error: Uncaught Error: Call to a member function querySingle() on null in /var/task/user/api/index.php:27 Stack trace: #0 {main} thrown in /var/task/user/api/index.php on line 27`

Thanks!

**Comment by f3l1x** [comment]
Sure it is. I have made a little demo for you.

https://github.com/juicyfx/vercel-examples/commit/13717d7964c5e357312b37c1ff2ed5865acc9a6a

> /api/index.php

```php
<?php

$db = new SQLite3('/tmp/db.sqlite', SQLITE3_OPEN_CREATE | SQLITE3_OPEN_READWRITE);

$db->query('CREATE TABLE IF NOT EXISTS "visits" (
    "id" INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    "url" VARCHAR,
    "time" DATETIME
)');

$statement = $db->prepare('INSERT INTO "visits" ("url", "time") VALUES (:url, :time)');
$statement->bindValue(':url', ($_SERVER['HTTP_X_FORWARDED_PROTO'] ?? 'https') . '://' . $_SERVER['HTTP_HOST'] . $_SERVER['REQUEST_URI']);
$statement->bindValue(':time', date('Y-m-d H:i:s'));
$statement->execute();

$visits = $db->querySingle('SELECT COUNT(id) FROM "visits"');

echo("User visits: $visits");

$db->close();
```

> now.json

```json
{
  "functions": {
    "api/index.php": {
      "runtime": "vercel-php@0.3.1"
    }
  },
  "routes": [
    { "src": "/(.*)",  "dest": "/api/index.php" }
  ]
}
```

**Comment by f3l1x** [comment]
Example URL here https://php-sqlite.vercel.app/

**Comment by khromov** [comment]
@f3l1x Sorry for bringing up an old thread, but what is the purpose of supporting SQLite? On every cold start, the database will be deleted or reset to its initial value... 

Maybe there's an interesting use case I'm not seeing?
